### ISSUE TITLE
Names for flash algorithms get inconsistent casing

### ISSUE THREAD

**Issue by mattiasgronlund** [probe-rs/target-gen#23]
When generating target files from .pack files the casing for the flash algorithms is sometimes inconsistent between the reference in the variant section and the definition in the flash_algorithm section.

End result being failure to flush as no matching algorithm is found.

**Comment by perlindgren** [comment]
Yes, this is a known problem. As for know you need to edit the yaml file to match cases. It seems the vendors live in case-less world ;)

**Comment by mattiasgronlund** [comment]
Ok, I just created my first pull request.

But I am not 100% sure this is the right solution.
The non updated code does lower case only the algorithm references from the chip types, but not the names used in the definition part, so it actually only worked if the filename was lower case.
So as the source for all instances of the name is from the file-name, only removing that to_lower_case() for the algorithm definitions might also work.
But I suppose depending on filename casing is a potential problem never the less.

**Comment by Yatekii** [comment]
Fixed in #24 :)
