### ISSUE TITLE
Why using PrgCode instead of .text?

### ISSUE THREAD

**Issue by AsafFisher** [probe-rs/target-gen#28]
I don't understand why do you use `PrgCode`/`PrgData` instead of `.text`/`.data` sections?

**Comment by Tiwalun** [comment]
We extract the flash algorithms from files which are provided by ARM and the chip vendors, called CMSIS-Packs.
The standard specifies that these sections are used.

I don't know why that choice was made, but now everyone using it.

**Comment by Yatekii** [comment]
This spec here: https://arm-software.github.io/CMSIS_5/Pack/html/flashAlgorithm.html

I think it would be possible to look for both section names.
